default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.27.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.2"]
